### ISSUE TITLE
Css unit should be rem rather than px - similar to bootstrap 5

### ISSUE THREAD

**Issue by Abdul007Malik** [zahinafsar/antd-css-utilities#1]

**Comment by zahinafsar** [comment]
Thanks for your request. We will consider it soon.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zahinafsar** [comment]
Still now "px" seems ok
