### ISSUE TITLE
Important rule removed?

### ISSUE THREAD

**Issue by adamblok** [zahinafsar/antd-css-utilities#4]
Any reason why the !important rule has been removed? In many cases it's not possible to overwrite some CSS properties using classes from antd-css-utilities, example:

Overwrite button margin property with ml-5 class:

```html
<button type="button" class="ant-btn css-dev-only-do-not-override-1lk7mw5 ant-btn-link ant-dropdown-trigger ml-5 fs-lg"><span>Add</span></button>
```

Result:

![image](https://github.com/zahinafsar/antd-css-utilities/assets/1498989/da249f37-cfac-4c78-a333-842018504116)

**Comment by zahinafsar** [comment]
Ops! That was a mistake we will fix that soon.

**Comment by zahinafsar** [comment]
We have fixed the issue. Please install version [2.0.4](https://www.npmjs.com/package/antd-css-utilities). Thanks for your feedback again.

**Comment by adamblok** [comment]
@zahinafsar Thanks!
