### ISSUE TITLE
No /*# sourceMappingURL=utility.min.css.map */ present

### ISSUE THREAD

**Issue by JulienLeotier** [zahinafsar/antd-css-utilities#5]
We have forget utility.min.css.map and vite return error

**Comment by zahinafsar** [comment]
Thanks for your feedback! We will fix that soon.

**Comment by zahinafsar** [comment]
We have fixed the issue. Please install version [2.0.4](https://www.npmjs.com/package/antd-css-utilities). Thanks for your feedback again.
