### ISSUE TITLE
px and py utilities override the entire padding property

### ISSUE THREAD

**Issue by busybox11** [zahinafsar/antd-css-utilities#6]
Hi!

I'm trying to use the `px` properties with `a-alert` to adjust the horizontal padding of this specific component usage.

When using only the `px-6` class, the horizontal padding is correct, but the default vertical padding is lost.
When using with `py-4`, the vertical padding is once again ignored.

<img width="325" alt="image" src="https://github.com/zahinafsar/antd-css-utilities/assets/29630035/c101edb7-a0a4-4d5b-84be-7132a5d4b825">

All the `px` and `py` utilities use a general `padding` property with `!important`, that is overriding all the sides regardless of the target.
In the CSS output, `px-6` is defined before `py-4`, that's why the latter doesn't get its CSS `padding` property applied.

I believe this library could use the same fine-grained padding definition as Tailwind to solve this problem.
If I take the output of `px-6`, they declare only `padding-left` and `padding-right` properties without `!important`, allowing the use of other padding utilities.
This can also be extended to general padding with an adjustment only on one side (let's say `p-4 pl-3`).

<img width="391" alt="image" src="https://github.com/zahinafsar/antd-css-utilities/assets/29630035/e6d55633-dbf3-4d4f-b172-064872ef2046">

Maybe this behavior is by design, hence why I'm posting this issue instead of making a PR. I'd like to have your opinion about this before making any changes.

Thanks!

**Comment by bydavid1** [comment]
I have the same issue

**Comment by zahinafsar** [comment]
Hi,

Thanks for your feedback! We just released a new version with the fix on [antd-css-utilities@2.0.5](https://www.npmjs.com/package/antd-css-utilities)
